trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - v*
jobs:
###########################################
- job: MacOS
###########################################
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: |
      echo "##vso[task.setvariable variable=HOME_DIRECTORY]$AGENT_HOMEDIRECTORY"
      echo "##vso[task.setvariable variable=BUILD_DIRECTORY]$BUILD_SOURCESDIRECTORY"
    displayName: 'Set variables'
  - bash: $(Build.SourcesDirectory)/.ci/test.sh
    displayName: Test
